---

- name: Configure the ec2 instance
  hosts: vm
  remote_user: ubuntu
  gather_facts: False
  sudo: true


  tasks:
    - name: Update the virtual machine
      apt: update_cache=yes

    - name: Install transport https and ca certificates
      apt: name={{item}} state=installed
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Add the GnuPG key to encrypt $ sign data
      command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: Check if the file docker.list exists in /etc/apt/sources.list.d/
      stat: path=/etc/apt/sources.list.d/docker.list
      register: var

    - name: Create the file docker.list if it is not existing in /etc/apt/sources.list.d/
      file: path=/etc/apt/sources.list.d/docker.list state=touch owner=root group=root mode=0644
      when: var.stat.exists is defined and not var.stat.exists

    - name: Edit docker.list file from /etc/apt/sources.list.d/
      lineinfile: dest=/etc/apt/sources.list.d/docker.list regexp=^deb 'line=deb https://apt.dockerproject.org/repo ubuntu-trusty main'

    - name: Update the virtual machine
      apt: update_cache=yes

    - name: Get the kernel release
      shell: uname -r
      register: uname
  
    - name: Install the image(Linux)
      apt: name=linux-image-extra-{{ uname.stdout }} state=present

### Reboot the vm
    
    - name: Update the virtual machine
      apt: update_cache=yes

    - name: Install docker engine
      apt: name=docker-engine state=present

    - name: Start docker service
      service: name=docker state=started
    
    - name: Add ubuntu user to docker group
      command: sudo usermod -aG docker ubuntu

    - name: Get docker compose
      shell: sudo curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose

    - name: Make docker compose executable
      shell: chmod +x /usr/local/bin/docker-compose

