---

- name: Deploy ELK stack on the virtual machine
  hosts: vm
  remote_user: ubuntu
  gather_facts: False


  tasks:

    - name: Copy ELK-stack configuration from docker/elk-stack to /home/ubuntu/
      copy: src=./docker/elk-stack dest=/home/ubuntu/

    - name: Build ELK docker images
      command: docker-compose -f ~/elk-stack/docker-elk.yml build

    - name: Start ELK services in docker container 
      command: docker-compose -f ~/elk-stack/docker-elk.yml up -d
